# Generated by Django 4.2.7 on 2024-01-15 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banking', '0002_transaction_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_when', models.DateTimeField()),
                ('modified_when', models.DateTimeField()),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('runs_on_already_classified_transactions', models.BooleanField(default=False)),
                ('runs_on_imported_transactions', models.BooleanField(default=True)),
                ('sorting', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RulesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean_type', models.CharField(choices=[('or', 'OR'), ('and', 'AND'), ('exclude_if', 'EXCLUDE IF')], max_length=20)),
                ('value_type', models.CharField(choices=[('na', 'Not applicable'), ('gt', 'Greather than'), ('gte', 'Greather than or equal to'), ('lt', 'Less than'), ('lte', 'Greather than or equal to'), ('equal', 'Equal to'), ('not_equal', 'Not equal to')], default='na', max_length=20)),
                ('value', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('description_type', models.CharField(choices=[('na', 'Not applicable'), ('equal', 'Exactly equal'), ('partial', 'Matchs parts'), ('starts_with', 'Starts with'), ('ends_with', 'Ends with')], default='na', max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('date_type', models.CharField(choices=[('na', 'Not applicable'), ('gt', 'Greather than'), ('gte', 'Greather than or equal to'), ('lt', 'Less than'), ('lte', 'Greather than or equal to'), ('equal', 'Equal to'), ('not_equal', 'Not equal to')], default='na', max_length=20)),
                ('competency_date', models.DateField(blank=True, null=True)),
                ('competency_date_type', models.CharField(choices=[('na', 'Not applicable'), ('gt', 'Greather than'), ('gte', 'Greather than or equal to'), ('lt', 'Less than'), ('lte', 'Greather than or equal to'), ('equal', 'Equal to'), ('not_equal', 'Not equal to')], default='na', max_length=20)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.account')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.rule')),
            ],
        ),
    ]
