# Generated by Django 4.2.7 on 2024-01-15 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_rule_rulesitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='apply_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.category'),
        ),
        migrations.AddField(
            model_name='rule',
            name='set_as_transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rulesitem',
            name='competency_date_type',
            field=models.CharField(choices=[('na', 'Not applicable'), ('gt', 'Greather than'), ('gte', 'Greather than or equal to'), ('lt', 'Less than'), ('lte', 'Greather than or equal to'), ('equal', 'Equal to')], default='na', max_length=20),
        ),
        migrations.AlterField(
            model_name='rulesitem',
            name='date_type',
            field=models.CharField(choices=[('na', 'Not applicable'), ('gt', 'Greather than'), ('gte', 'Greather than or equal to'), ('lt', 'Less than'), ('lte', 'Greather than or equal to'), ('equal', 'Equal to')], default='na', max_length=20),
        ),
        migrations.AlterField(
            model_name='rulesitem',
            name='description_type',
            field=models.CharField(choices=[('na', 'Not applicable'), ('iexact', 'Exactly equal'), ('icontains', 'Matchs parts'), ('istartswith', 'Starts with'), ('iendswith', 'Ends with')], default='na', max_length=20),
        ),
        migrations.AlterField(
            model_name='rulesitem',
            name='value_type',
            field=models.CharField(choices=[('na', 'Not applicable'), ('gt', 'Greather than'), ('gte', 'Greather than or equal to'), ('lt', 'Less than'), ('lte', 'Greather than or equal to'), ('equal', 'Equal to')], default='na', max_length=20),
        ),
    ]
