# Generated by Django 4.2.7 on 2024-05-10 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_rule_apply_category_rule_set_as_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='incur_on_competency',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='apply_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.category'),
        ),
    ]
