# Generated by Django 4.2.11 on 2024-06-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_account_incur_on_competency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='budget_incur_type',
            field=models.CharField(blank=True, choices=[('', 'Account Default'), ('C', 'Competency Date'), ('T', 'Transaction Date')], max_length=1, null=True),
        ),
    ]
